//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCase1.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WsrUser7Entities : DbContext
    {
        public WsrUser7Entities()
            : base("name=WsrUser7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<LoyaltyCard> LoyaltyCard { get; set; }
        public virtual DbSet<Movement> Movement { get; set; }
        public virtual DbSet<OpeningHour> OpeningHour { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<PointOfSale> PointOfSale { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TrafficPaht> TrafficPaht { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
