//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCase1.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficPaht
    {
        public int Id { get; set; }
        public Nullable<int> PointOfSale { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Direction { get; set; }
    
        public virtual PointOfSale PointOfSale1 { get; set; }
    }
}
